name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        # Whitelist Semantic Scholar (returns 202 for async page loading)
        args: --allow-dupe --allow-redirect --white-list "www.semanticscholar.org" /github/workspace/README.md
